services:
  db:
    image: postgres:17.5-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-todo-with-auth0}-db
    restart: on-failure
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-todo-with-auth0-password}
      POSTGRES_DB: ${POSTGRES_DB:-todo-with-auth0}
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=en_US.utf8'
    ports:
      - '${POSTGRES_PORT:-6432}:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U postgres -d ${POSTGRES_DB:-todo-with-auth0}',
        ]
      interval: 5s
      timeout: 2s
      retries: 2
      start_period: 10s
  redis:
    image: redis:8.0-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-todo-with-auth0}-redis
    restart: on-failure
    security_opt:
      - no-new-privileges:true
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-todo-with-auth0-password} --maxmemory 256mb --maxmemory-policy noeviction
    volumes:
      - redis-cache:/data
    networks:
      - backend
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 2s
      retries: 2
      start_period: 10s
volumes:
  db-data:
  redis-cache:
networks:
  backend:
    driver: bridge
